# The https://github.com/matrix-org/matrix-federation-tester instance to use.
# {server} is replaced with the server name.
federation_tester: https://matrix.org/federationtester/api/report?server_name={server}
